### ISSUE TITLE
How do you use this wrapper?

### ISSUE THREAD

**Issue by Ma0us** [basicx-StrgV/WGet.NET#1]
I can't find any documentation or code examples, please tell me how to use this wrapper

**Comment by Ma0us** [comment]
Thanks for the quick reply, how do i search using this wrapper?

**Comment by basicx-StrgV** [comment]
Searching for packages can be done like this:
```csharp
WinGetPackageManager packageManager = new WinGetPackageManager();
List<WinGetPackage> packages = packageManager.SearchPackage("Git");
```

**Comment by Ma0us** [comment]
Thank you!
