### ISSUE TITLE
Why would `GetInstalledPackages` return 2 when `winget show` returns 1?

### ISSUE THREAD

**Issue by MrHinsh** [basicx-StrgV/WGet.NET#22]
For some reason when I do `packageManager.GetInstalledPackages("nkdAgility.AzureDevOpsMigrationTools")` I get two identical elements returned.

But when I run `winget show nkdAgility.AzureDevOpsMigrationTools` I get only 1 item returned

Any ideas?

![image](https://github.com/basicx-StrgV/WGet.NET/assets/5205575/052ef7a6-779c-47c5-be7a-9dcb40aed22f)

**Comment by basicx-StrgV** [comment]
The action performed by winget, when using `GetInstalledPackages("nkdAgility.AzureDevOpsMigrationTools")` is equal to `winget list nkdAgility.AzureDevOpsMigrationTools`. Can you please check what the output for this action is for you.

The two objects seem to be identical, so it is probably a bug in the library and not the winget output. 
I will see if I can reproduce and fix the problem.

**Comment by basicx-StrgV** [comment]
Ok, that is interesting. Are there by any chance two installed instances of the software on the system?

What happens if you use the following command `winget list “nkdAgility.AzureDevOpsMigrationTools” -e`.

**Comment by MrHinsh** [comment]
```
❯ winget list nkdAgility.AzureDevOpsMigrationTools -e
No installed package found matching input criteria.
```

**Comment by basicx-StrgV** [comment]
Yes, this is what I expected to happen, just needed to double check.

I saw that you already created an issue for the winget-cli. We might need to wait and see what information we can get from that.

But if possible, you could try to manually uninstall both instances of you tool and the reinstall them with winget, to see if this fixes the problem.

**Comment by basicx-StrgV** [comment]
Also, could it be that WinGet detects the version that you are running in the debugger as the second version?
It’s just an idea but might be worth to check.
