### ISSUE TITLE
Hang for `WinGet winget = new WinGet();`

### ISSUE THREAD

**Issue by MrHinsh** [basicx-StrgV/WGet.NET#32]
I have some users reporting a hang on initilisation of the tool on Windows Server and some Windows 11 platforms.

I assume Winget is not installed.

**Comment by basicx-StrgV** [comment]
I will take a look at it.

It could be that there is a bug that will cause it to hang if winget is not installed.

**Comment by basicx-StrgV** [comment]
I released a patch (Version 4.0.1) that should fix the issue.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/4.0.1
