### ISSUE TITLE
A typo in the upgrade all command

### ISSUE THREAD

**Issue by itzwolly** [basicx-StrgV/WGet.NET#37]
**Describe the bug**
A typo in the 'upgrade all' command inside the WinGetPackageManager.cs.

**To Reproduce**
1. Go to WinGetPackageManager.cs
2. Go to line: 29
3. Observe => `private const string _upgradeAllCmd = "upgrade --al --accept-source-agreementsl";`

**Expected behavior**
Command should be: `private const string _upgradeAllCmd = "upgrade --all --accept-source-agreements";`

**Screenshots**
N/A

**Package Version**
v4.1.0

**Additional context**
N/A

**Comment by basicx-StrgV** [comment]
I released a patch (Version 4.1.1) containing a fix for this issue.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/4.1.1
