### ISSUE TITLE
List command requests user to accept source agreements

### ISSUE THREAD

**Issue by itzwolly** [basicx-StrgV/WGet.NET#38]
**Describe the bug**
Calling the 'list' command in winget prompts the user to accept the source agreements. The 'list' command currently does not include the '--accept-source-agreements' flag.

**To Reproduce**
1. Go to WinGetPackageManager.cs.
2. Go to lines: 20, 22, or 24.
3. Observe that these lines do not include bypassing the source agreements.

**Expected behavior**
In order to bypass the source agreements when calling the 'list' command, I'd expect the command to include the ''--accept-source-agreements" flag.

**Screenshots**
N/A

**Package Version**
4.1.0

**Additional context**
I believe that only recently the 'list' command prompts for the source agreements, but I'm unable to verify when this has been added/changed.

**Comment by itzwolly** [comment]
Microsoft docs containing: '--accept-source-agreement' as flag for winget list: https://learn.microsoft.com/en-us/windows/package-manager/winget/list

**Comment by Skio22** [comment]
I would appreciate it if you could add this flag as well, because today I noticed that Winget behaves oddly and does not return any apps without it.

**Comment by basicx-StrgV** [comment]
I will release a patch that should fix this and other current issues as soon as possible.

**Comment by basicx-StrgV** [comment]
I released a patch (Version 4.1.1) containing a fix for this issue.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/4.1.1
